### ISSUE TITLE
支持 file_merge 资源

### ISSUE THREAD

**Issue by zuowenjian** [xcodecraft/rigger-ng#15]
``` yaml
      -  !R.system
          _name: "merge"
          _res:
              - !R.file_merge
                  dst : "${PRJ_ROOT}/test/data/merge/result.yaml"
                  src : "${PRJ_ROOT}/test/data/merge/"
                  filter : "^include.+yaml$"

```
