### ISSUE TITLE
support auto start

### ISSUE THREAD

**Issue by zuowenjian** [xcodecraft/rigger-ng#36]
project system need  auto start when the host system restart.

**Comment by zuowenjian** [comment]
support will  like this :
```yaml
    -  !R.system
        _name: "test"
        _serv:
            auto : "online"
       _res :
            ...
```
